### ISSUE TITLE
Peer code review

### ISSUE THREAD

**Issue by masangana** [waqaskanju/awesome_books#8]
Hello **### Team**.
You did a great job. Your code are clear and fair. No comment about it. The result is awesome.
I would just give my feedback about the add function.
The way you use to manage the id is laborious. Using the index table would be easiest. But your code is workin and the result is good. 💯

**Comment by BregornOriginal** [comment]
**Hi Tom! Nice job! 👏**

- We were looking at the project this morning season and it looks very nice. 

- We couldn't find some issues here. 

*This is so clean, works properly, and meets the project requirements.*

Keep coding,
Best!🍾
